---
title: "C# Basic - 18: Exception Handling"
permalink: cs-basic-18/                # link 직접 지정
toc: true                       # for Sub-title (On this page)
comments: true                  # for disqus Comments
categories:                     # for categories
date: 2020-08-16 00:00:00 -0000
last_modified_at: 2020-08-16 00:00:00 -0000
sidebar:
  title: "C# 목차"
  nav: cs
tag:
  - C#
category:
  - Basic 18
  - Exception Handling
excerpt: ""
header:
  teaser: /file/image/cs-page-teaser.gif
---

```csharp
public static class FileManager
{
    public static int CopyFile(string srcFileName, string dstFileName)
    {
        // ... 파일을 복사하다가 실패했다고 가정해보자.

        return 100;
    }
}
class Program
{
    static void Main()
    {
        FileManager.CopyFile("C:\\a.txt", "D:\\b.txt");
    }
}
```

```csharp
// 이런식의 처리도 가능하다
public static class FileManager
{
    public static int CopyFile(string srcFileName, string dstFileName, out int len)
    {
        // ... 
        len = 100;
        return 100;
    }
}
class Program
{
    static void Main()
    {
        FileManager.CopyFile("C:\\a.txt", "D:\\b.txt", out len);
    }
}
```

```csharp
// 위와 같은 모델은 C#에서 주로 활용된다.
string s = "10";
// string s = "ddd";

int num;
bool b = int.TryParse(s, out num);

// 파싱의 결과는 b에
// 파싱이 된 숫자는 num에 넣어달라
```

---

```csharp
public static class FileManager
{
    public static int CopyFile(string srcFileName, string dstFileName)
    {
        throw new Exception("파일 접근 오류");

        return 100;
    }
}
class Program
{
    static void Main()
    {
        try {
            FileManager.CopyFile("C:\\a.txt", "D:\\b.txt");
        }
        catch(Exception e)
        {
            Console.WriteLine(e.Message);
        }
        
    }
}
```

---

```csharp
static void Main()
{
    WebClient wc = new WebClient();
    string s = wc.DownloadString("http://www.naver.com");
    // 만약 접속 실패가 된다면? -> Exception 발생!!
    // Exception을 처리해보자.
    Console.WriteLine(s);
}
```

```csharp
static void Main()
{
    try { 
        WebClient wc = new WebClient();
        string s = wc.DownloadString("http://www.naver.com");
        // 만약 접속 실패가 된다면? -> Exception 발생!!
        // Exception을 처리해보자.
        Console.WriteLine(s);
    }
    catch(System.ArgumentNullException e)
    {

    }
    catch(System.Exception e)
    {

    }
}
```

```csharp
public static void Goo()
{
    int[] arr = { 1, 2, 3 };
    arr[3] = 10;        // 아마 여기서 에러가 발생할 것
}
public static void Foo()
{
    Goo();
}
static void Main()
{
    Foo();
}
```

```csharp
public static void Goo()
{
    int[] arr = { 1, 2, 3 };
    arr[3] = 10;        // 아마 여기서 에러가 발생할 것
}
public static void Foo()
{
    Goo();
}
static void Main()
{
    try{
        Foo();
    }
    catch(IndexOutOfRangeException e)
    {
        Console.WriteLine(e.Message);           // 예외를 설명하는 문자열
        Console.WriteLine(e.StackTrace);        // 예외의 근원지 부터 catch 블록에 도달할때까지 메소드 출력
    }
}
```